
export const GET_COUNTRIES = 'App/GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = 'App/GET_COUNTRIES_SUCCESS';
export const HANDLE_CONFIRM_OPEN = 'App/HANDLE_CONFIRM_OPEN';
export const HANDLE_CONFIRM_CLOSE = 'App/HANDLE_CONFIRM_CLOSE';
